Phase 2 in rails blog app
sujanadiga-practo/blog-rails pull request #2
Opened 2016-09-29 18:17 UTC by sujanadiga-practo

###What ?
- Use haml in views instead of erb

### Why ?
- Ease of writing views in haml

2016-10-06 13:25 UTC, tarunjadhwani requested changes

2016-10-06 13:25 UTC, tarunjadhwani commented on Gemfile.lock
>        thread_safe (~> 0.3, >= 0.3.4)
not needed in git

2016-10-06 13:25 UTC, tarunjadhwani commented on Gemfile
> +gem 'haml'
should have versions

2016-10-06 13:25 UTC, tarunjadhwani commented on app/controllers/application_controller.rb
> +  def after_sign_out_path_for(resource_or_scope)
can include after sign in path also that should be on root path, and after signout should ideally have login page

2016-10-06 13:25 UTC, tarunjadhwani commented on app/controllers/articles_controller.rb
> +  before_filter :authenticate_user!
this should be in applicationController, so that we dont have to add in all controllers

2016-10-06 13:25 UTC, tarunjadhwani commented on app/views/comments/_form.html.haml
> +    = f.submit 'POST', :class => 'btn btn--block comment-post'
use class: "adsfasldkf" notation

2016-10-06 13:25 UTC, tarunjadhwani commented on app/views/layouts/application.html.haml
> +  = stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,500italic,700,700italic|Roboto+Mono:400,500,700|Material+Icons'
don't think this is the right palce. it should be in applciation.css

2016-10-06 13:25 UTC, tarunjadhwani commented on config/routes.rb
> +  devise_for :users
check all the routes it generates. check if we are using all `rake routes`

2016-10-06 13:25 UTC, tarunjadhwani commented on db/schema.rb
>  #
this can also be skipped in github

2016-10-06 13:25 UTC, tarunjadhwani commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
read about all moduels

2016-10-06 13:40 UTC, sujanadiga-practo commented on db/schema.rb
>  #
Having this in repo is fine for my use case.

2016-10-06 13:46 UTC, sujanadiga-practo commented on app/controllers/application_controller.rb
> +  def after_sign_out_path_for(resource_or_scope)
This function is been removed in next PRs, this function is redundant in current application for current use case

2016-10-07 06:01 UTC, sujanadiga-practo commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
👍 
BTW remember me sets cookie with expiration to 2 weeks in future.

2016-10-07 06:02 UTC, sujanadiga-practo commented on Gemfile.lock
>        thread_safe (~> 0.3, >= 0.3.4)
Ignored in .gitignore

2016-10-07 06:02 UTC, sujanadiga-practo commented on Gemfile
> +gem 'haml'
Added versions

2016-10-07 06:02 UTC, sujanadiga-practo commented on app/controllers/articles_controller.rb
> +  before_filter :authenticate_user!
Moved to application controller

2016-10-07 06:15 UTC, sujanadiga-practo commented on app/views/layouts/application.html.haml
> +  = stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,500italic,700,700italic|Roboto+Mono:400,500,700|Material+Icons'
Moved to vendor/stylesheets

2016-10-07 07:09 UTC, sujanadiga-practo commented on config/routes.rb
> +  devise_for :users
Checked, all the devise routes are required for one or other purpose
```
        new_user_session GET    /users/sign_in(.:format)           devise/sessions#new          User signin form
            user_session POST   /users/sign_in(.:format)           devise/sessions#create       User signin
    destroy_user_session DELETE /users/sign_out(.:format)          devise/sessions#destroy      User signout
           user_password POST   /users/password(.:format)          devise/passwords#create      Send instructions email in forgot password
       new_user_password GET    /users/password/new(.:format)      devise/passwords#new         Forgot your password? form
      edit_user_password GET    /users/password/edit(.:format)     devise/passwords#edit        Create new password form in forgot password
                         PATCH  /users/password(.:format)          devise/passwords#update      Update password - Forgot password
                         PUT    /users/password(.:format)          devise/passwords#update      Update password - Forgot password
       user_registration POST   /users(.:format)                   devise/registrations#create  New user signup
   new_user_registration GET    /users/sign_up(.:format)           devise/registrations#new     New user signup form
  edit_user_registration GET    /users/edit(.:format)              devise/registrations#edit    Edit user details
                         PATCH  /users(.:format)                   devise/registrations#update  Update user details
                         PUT    /users(.:format)                   devise/registrations#update  Update user details
                         DELETE /users(.:format)                   devise/registrations#destroy Remove user account
       user_confirmation POST   /users/confirmation(.:format)      devise/confirmations#create  Send confirmation email
   new_user_confirmation GET    /users/confirmation/new(.:format)  devise/confirmations#new     Send confirmation email form
                         GET    /users/confirmation(.:format)      devise/confirmations#show    Email confirmation link
```

2016-10-07 07:16 UTC, sujanadiga commented on app/views/comments/_form.html.haml
> +    = f.submit 'POST', :class => 'btn btn--block comment-post'
👍

2016-10-07 11:03 UTC, tarunjadhwani approved these changes

2016-10-07 11:04 UTC, merged