Environment and polishing
sujanadiga-practo/blog-rails pull request #4
Opened 2016-10-06 12:47 UTC by sujanadiga-practo

### What?
- Using mysql
- Using secrets.yml
- Difference between running rails in dev and production
- Polishing and DRYing out the code

### Why?
- To understand different environments to run rails and identify the differences
- Make use of secrets.yml for storing sensitive configs

2016-10-14 18:38 UTC, tarunjadhwani requested changes

2016-10-14 18:38 UTC, tarunjadhwani commented on app/controllers/comments_controller.rb
> +    @user = current_user
isn't current_user accessible in views also? you can remove this one then.

2016-10-14 18:38 UTC, tarunjadhwani commented on app/controllers/comments_controller.rb
> +    @comment = @article.comments.create({message: params[:comment][:message], user_id: @user.id})
@user is not required here. Use the curent_user object.

2016-10-14 18:38 UTC, tarunjadhwani commented on app/controllers/comments_controller.rb
> -    def comment_params
This function is important here. works as whitelist instead of blacklist.

2016-10-14 18:38 UTC, tarunjadhwani commented on app/controllers/articles_controller.rb
> +    def get_user
why don't you use current user directly?

2016-10-14 18:38 UTC, tarunjadhwani commented on db/migrate/20161004124232_add_user_id_to_article.rb
> +      t.belongs_to :user, index: true, foreign_key: true
foreign_key not needed?

2016-10-14 19:01 UTC, tarunjadhwani commented
Since you have made this branch as polishing, adding the overall scope of improvements also here:
- [ ] gemfile should have ruby version
- [ ] $(document).ready(-> $('time.timeago').timeago()) not a good thing to have it like this. Should be a function and called where ever required.
- [ ] Read kishore's article on sensible defaults
- [ ] After you have signed up you should be signed in directly
- [ ] Read on how to generate secert key base (ignore if already did)
- [ ] Completed 401 Unauthorized in 150ms (ActiveRecord: 0.6ms) (getting this error not able to login (keep user informed with proper error messages in all forms)
- [ ] Unique validation need to be handled at rails model level and not at database level
Please resolve the issue with login and will continue will look into the app further.

2016-10-15 12:16 UTC, sujanadiga-practo commented on app/controllers/comments_controller.rb
> -    def comment_params
I removed this function because I am manually sending only params[:comment][:message] field to create function

2016-10-18 05:28 UTC, tarunjadhwani approved these changes

2016-10-18 05:42 UTC, merged